# Generated by Django 4.0.2 on 2022-02-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.CharField(choices=[('MANAGEMENT', 'MANAGEMENT'), ('SALES', 'SALES'), ('SUPPORT', 'SUPPORT')], default='MANAGEMENT', max_length=10),
        ),
    ]
