# Generated by Django 4.0.2 on 2022-03-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
    ]
